import type { Metadata } from "next";
import { Heebo } from "next/font/google";
import "./globals.css";
import NavbarDemo from "@/components/elements/NavBar";
import { Fraunces } from 'next/font/google'

export const fraunces = Fraunces({
  subsets: ['latin'],
  weight: ['400', '700'],
})

const heebo = Heebo({
  variable: "--font-heebo",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Soraia Felix",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${heebo.variable} antialiased`}
      > 
        <NavbarDemo />
        {children}
      </body>
    </html>
  );
}
